####################################
#  Parameter vectors
####################################

numplots <- length(levels(ocells$Especie))
nplots<-numplots


# Initial parameters ------------------------------------------------------

par_model <- list(null_null_null_par = list(PotRichness = 1, 
                                        lambda=1),
                  
                ##### Pentavariate  and tetravariate initial parameters ####
                penta_complete_par = list(PotRichness = 1,
                                        Densi_a=40,Densi_b=2,
                                        Quadr_a = 30, Quadr_b = 10,
                                        DHeig_a=10, DHeig_b=2, 
                                        Cavit_a=81, Cavit_b=2,
                                        Shrub_a=50, Shrub_b=20,
                                        lambda=1),
                
                tetra_no_Shrub_par = list(PotRichness = 1,
                                        Densi_a=40,Densi_b=2,
                                        Quadr_a = 30, Quadr_b = 10,
                                        DHeig_a=10, DHeig_b=2, 
                                        Cavit_a=81, Cavit_b=2,
                                        lambda=1),
                tetra_no_Cavit_par = list(PotRichness = 1,
                                        Densi_a=40,Densi_b=2,
                                        Quadr_a = 30, Quadr_b = 10,
                                        DHeig_a=10, DHeig_b=2, 
                                        Shrub_a=50, Shrub_b=20,
                                        lambda=1),
                tetra_no_DHeig_par = list(PotRichness = 1,
                                        Densi_a=40,Densi_b=2,
                                        Quadr_a = 30, Quadr_b = 10,
                                        Cavit_a=81, Cavit_b=2,
                                        Shrub_a=50, Shrub_b=20,
                                        lambda=1),
                tetra_no_Quadr_par = list(PotRichness = 1,
                                        Densi_a=40,Densi_b=2,
                                        DHeig_a=10, DHeig_b=2, 
                                        Cavit_a=81, Cavit_b=2,
                                        Shrub_a=50, Shrub_b=20,
                                        lambda=1),
                tetra_no_Densi_par = list(PotRichness = 1,
                                        Quadr_a = 30, Quadr_b = 10,
                                        DHeig_a=10, DHeig_b=2, 
                                        Cavit_a=81, Cavit_b=2,
                                        Shrub_a=50, Shrub_b=20,
                                        lambda=1),
                tetra_complete_par = list(PotRichness = 1,
                                        Basal_a=40,Basal_b=2,
                                        DHeig_a=10, DHeig_b=2, 
                                        Cavit_a=81, Cavit_b=2,
                                        Shrub_a=50, Shrub_b=20,
                                        lambda=1),
                
                ##### Trivariate initial parameters ####
                no_Shrub_Cavit_par = list(PotRichness = 1,
                                        Densi_a=40,Densi_b=2,
                                        Quadr_a = 30, Quadr_b = 10,
                                        DHeig_a=10, DHeig_b=2, 
                                        lambda=1),
                no_Shrub_DHeig_par = list(PotRichness = 1,
                                        Densi_a=40,Densi_b=2,
                                        Quadr_a = 30, Quadr_b = 10,
                                        Cavit_a=81, Cavit_b=2,
                                        lambda=1),
                no_Shrub_Quadr_par = list(PotRichness = 1,
                                        Densi_a=40,Densi_b=2,
                                        DHeig_a=10, DHeig_b=2, 
                                        Cavit_a=81, Cavit_b=2,
                                        lambda=1),
                no_Shrub_Densi_par = list(PotRichness = 1,
                                        Quadr_a = 30, Quadr_b = 10,
                                        DHeig_a=10, DHeig_b=2, 
                                        Cavit_a=81, Cavit_b=2,
                                        lambda=1),
                no_Cavit_DHeig_par = list(PotRichness = 1,
                                        Densi_a=40,Densi_b=2,
                                        Quadr_a = 30, Quadr_b = 10,
                                        Shrub_a=50, Shrub_b=20,
                                        lambda=1),
                no_Cavit_Quadr_par = list(PotRichness = 1,
                                        Densi_a=40,Densi_b=2,
                                        DHeig_a=10, DHeig_b=2, 
                                        Shrub_a=50, Shrub_b=20,
                                        lambda=1),
                no_Cavit_Densi_par = list(PotRichness = 1,
                                        Quadr_a = 30, Quadr_b = 10,
                                        DHeig_a=10, DHeig_b=2, 
                                        Shrub_a=50, Shrub_b=20,
                                        lambda=1),
                no_DHeig_Quadr_par = list(PotRichness = 1,
                                        Densi_a=40,Densi_b=2,
                                        Cavit_a=81, Cavit_b=2,
                                        Shrub_a=50, Shrub_b=20,
                                        lambda=1),
                no_DHeig_Densi_par = list(PotRichness = 1,
                                        Quadr_a = 30, Quadr_b = 10,
                                        Cavit_a=81, Cavit_b=2,
                                        Shrub_a=50, Shrub_b=20,
                                        lambda=1),
                no_Quadr_Densi_par = list(PotRichness = 1,
                                        DHeig_a=10, DHeig_b=2, 
                                        Cavit_a=81, Cavit_b=2,
                                        Shrub_a=50, Shrub_b=20,
                                        lambda=1),
                compl_no_Shrub_par = list(PotRichness = 1,
                                        Basal_a=40,Basal_b=2,
                                        DHeig_a=10, DHeig_b=2, 
                                        Cavit_a=81, Cavit_b=2,
                                        lambda=1),
                compl_no_Cavit_par = list(PotRichness = 1,
                                        Basal_a=40,Basal_b=2,
                                        DHeig_a=10, DHeig_b=2, 
                                        Shrub_a=50, Shrub_b=20,
                                        lambda=1),
                compl_no_DHeig_par = list(PotRichness = 1,
                                        Basal_a=40,Basal_b=2,
                                        Cavit_a=81, Cavit_b=2,
                                        Shrub_a=50, Shrub_b=20,
                                        lambda=1),
                
                ##### Bivariate initial parameters #####
                
                bi_Densi_Quadr_par = list(PotRichness = 1,
                                       Densi_a=40,Densi_b=2,
                                       Quadr_a = 30, Quadr_b = 10,
                                       lambda=1),
                bi_Densi_DHeig_par = list(PotRichness = 1,
                                       Densi_a=40,Densi_b=2,
                                       DHeig_a=10, DHeig_b=2, 
                                       lambda=1),
                bi_Densi_Cavit_par = list(PotRichness = 1,
                                       Densi_a=40,Densi_b=2,
                                       Cavit_a=81, Cavit_b=2,
                                       lambda=1),
                bi_Densi_Shrub_par = list(PotRichness = 1,
                                       Densi_a=40,Densi_b=2,
                                       Shrub_a=50, Shrub_b=20,
                                       lambda=1),
                bi_Quadr_DHeig_par = list(PotRichness = 1,
                                       Quadr_a = 30, Quadr_b = 10,
                                       DHeig_a=10, DHeig_b=2, 
                                       lambda=1),
                bi_Quadr_Cavit_par = list(PotRichness = 1,
                                       Quadr_a = 30, Quadr_b = 10,
                                       Cavit_a=81, Cavit_b=2,
                                       lambda=1),
                bi_Quadr_Shrub_par = list(PotRichness = 1,
                                       Quadr_a = 30, Quadr_b = 10,
                                       Shrub_a=50, Shrub_b=20,
                                       lambda=1),
                bi_DHeig_Cavit_par = list(PotRichness = 1,
                                       DHeig_a=10, DHeig_b=2, 
                                       Cavit_a=81, Cavit_b=2,
                                       lambda=1),
                bi_DHeig_Shrub_par = list(PotRichness = 1,
                                       DHeig_a=10, DHeig_b=2, 
                                       Shrub_a=50, Shrub_b=20,
                                       lambda=1),
                bi_Cavit_Shrub_par = list(PotRichness = 1,
                                       Cavit_a=81, Cavit_b=2,
                                       Shrub_a=50, Shrub_b=20,
                                       lambda=1),
                bi_Basal_DHeig_par = list(PotRichness = 1,
                                       Basal_a=40,Basal_b=2,
                                       DHeig_a=10, DHeig_b=2, 
                                       lambda=1),
                bi_Basal_Cavit_par = list(PotRichness = 1,
                                       Basal_a=40,Basal_b=2,
                                       Cavit_a=81, Cavit_b=2,
                                       lambda=1),
                bi_Basal_Shrub_par = list(PotRichness = 1,
                                       Basal_a=40,Basal_b=2,
                                       Shrub_a=50, Shrub_b=20,
                                       lambda=1),
                
                ##### Univariate initial parameters  #####
                
                univaria_Basal_par = list (PotRichness = 1,
                                     Basal_a = 40, Basal_b = 2, 
                                     lambda = 1),
                univaria_Densi_par = list (PotRichness = 1,
                                         Densi_a = 500, Densi_b = 100, 
                                         lambda = 1),
                univaria_Quadr_par = list (PotRichness = 1,
                                         Quadr_a = 20, Quadr_b = 20, 
                                         lambda = 1),
                univaria_DHeig_par = list (PotRichness = 1,
                                         DHeig_a = 10, DHeig_b = 2, 
                                         lambda = 1),
                univaria_Cavit_par = list (PotRichness = 1,
                                     Cavit_a = 81, Cavit_b = 2, 
                                     lambda = 1),
                univaria_Shrub_par = list (PotRichness = 1,
                                     Shrub_a = 50, Shrub_b = 20, 
                                     lambda = 1),
                univaria_DVari_par = list (PotRichness = 1,
                                     DVari_a = 50, DVari_b = 20, 
                                     lambda = 1),
                univaria_Snags_par = list (PotRichness = 1,
                                         Snags_a = 250, Snags_b = 120, 
                                         lambda = 1),
                univaria_Herba_par = list (PotRichness = 1,
                                           Herba_a = 50, Herba_b = 20, 
                                           lambda = 1),
                univaria_Thick_par = list (PotRichness = 1,
                                           Thick_a = 50, Thick_b = 20, 
                                           lambda = 1)
                )
                

# Low parameters ------------------------------------------------------

par_low <- list(null_null_null_par_lo = list(PotRichness = 0, 
                                        lambda=0.0001),
                
                ##### Pentavariate  and tetravariate low parameters #####
                
                penta_complete_par_lo = list(PotRichness = 0,
                                          Densi_a=0.00001,Densi_b=0.00001,
                                          Quadr_a = 0.00001, Quadr_b = 0.00001,
                                          DHeig_a=0.00001, DHeig_b=0.00001,
                                          Cavit_a=0.00001, Cavit_b=0.00001,
                                          Shrub_a=0.00001, Shrub_b=0.00001,
                                          lambda=0.00001),
                
                tetra_no_Shrub_par_lo = list(PotRichness = 0,
                                             Densi_a=0.00001,Densi_b=0.00001,
                                             Quadr_a = 0.00001, Quadr_b = 0.00001,
                                             DHeig_a=0.00001, DHeig_b=0.00001,
                                             Cavit_a=0.00001, Cavit_b=0.00001,
                                             lambda=0.00001),
                tetra_no_Cavit_par_lo = list(PotRichness = 0,
                                             Densi_a=0.00001,Densi_b=0.00001,
                                             Quadr_a = 0.00001, Quadr_b = 0.00001,
                                             DHeig_a=0.00001, DHeig_b=0.00001,
                                             Shrub_a=0.00001, Shrub_b=0.00001,
                                             lambda=0.00001),
                tetra_no_DHeig_par_lo = list(PotRichness = 0,
                                             Densi_a=0.00001,Densi_b=0.00001,
                                             Quadr_a = 0.00001, Quadr_b = 0.00001,
                                             Cavit_a=0.00001, Cavit_b=0.00001,
                                             Shrub_a=0.00001, Shrub_b=0.00001,
                                             lambda=0.00001),
                tetra_no_Quadr_par_lo = list(PotRichness = 0,
                                             Densi_a=0.00001,Densi_b=0.00001,
                                             DHeig_a=0.00001, DHeig_b=0.00001,
                                             Cavit_a=0.00001, Cavit_b=0.00001,
                                             Shrub_a=0.00001, Shrub_b=0.00001,
                                             lambda=0.00001),
                tetra_no_Densi_par_lo = list(PotRichness = 0,
                                             Quadr_a = 0.00001, Quadr_b = 0.00001,
                                             DHeig_a=0.00001, DHeig_b=0.00001,
                                             Cavit_a=0.00001, Cavit_b=0.00001,
                                             Shrub_a=0.00001, Shrub_b=0.00001,
                                             lambda=0.00001),
                tetra_complete_par_lo = list(PotRichness = 0,
                                             Basal_a=0.00001, Basal_b=0.00001, 
                                             DHeig_a=0.00001, DHeig_b=0.00001,
                                             Cavit_a=0.00001, Cavit_b=0.00001,
                                             Shrub_a= 0.00001,Shrub_b=0.000001,
                                             lambda=0.00001),
                
                ##### Trivariate low parameters #####
                no_Shrub_Cavit_par_lo = list(PotRichness = 0,
                                             Densi_a=0.00001,Densi_b=0.00001,
                                             Quadr_a = 0.00001, Quadr_b = 0.00001,
                                             DHeig_a=0.00001, DHeig_b=0.00001,
                                             lambda=0.00001),
                no_Shrub_DHeig_par_lo = list(PotRichness = 0,
                                             Densi_a=0.00001,Densi_b=0.00001,
                                             Quadr_a = 0.00001, Quadr_b = 0.00001,
                                             Cavit_a=0.00001, Cavit_b=0.00001,
                                             lambda=0.00001),
                no_Shrub_Quadr_par_lo = list(PotRichness = 0,
                                             Densi_a=0.00001,Densi_b=0.00001,
                                             DHeig_a=0.00001, DHeig_b=0.00001,
                                             Cavit_a=0.00001, Cavit_b=0.00001,
                                             lambda=0.00001),
                no_Shrub_Densi_par_lo = list(PotRichness = 0,
                                             Quadr_a = 0.00001, Quadr_b = 0.00001,
                                             DHeig_a=0.00001, DHeig_b=0.00001,
                                             Cavit_a=0.00001, Cavit_b=0.00001,
                                             lambda=0.00001),
                no_Cavit_DHeig_par_lo = list(PotRichness = 0,
                                             Densi_a=0.00001,Densi_b=0.00001,
                                             Quadr_a = 0.00001, Quadr_b = 0.00001,
                                             Shrub_a=0.00001, Shrub_b=0.00001,
                                             lambda=0.00001),
                no_Cavit_Quadr_par_lo = list(PotRichness = 0,
                                             Densi_a=0.00001,Densi_b=0.00001,
                                             DHeig_a=0.00001, DHeig_b=0.00001,
                                             Shrub_a=0.00001, Shrub_b=0.00001,
                                             lambda=0.00001),
                no_Cavit_Densi_par_lo = list(PotRichness = 0,
                                             Quadr_a = 0.00001, Quadr_b = 0.00001,
                                             DHeig_a=0.00001, DHeig_b=0.00001,
                                             Shrub_a=0.00001, Shrub_b=0.00001,
                                             lambda=0.00001),
                no_DHeig_Quadr_par_lo = list(PotRichness = 0,
                                             Densi_a=0.00001,Densi_b=0.00001,
                                             Cavit_a=0.00001, Cavit_b=0.00001,
                                             Shrub_a=0.00001, Shrub_b=0.00001,
                                             lambda=0.00001),
                no_DHeig_Densi_par_lo = list(PotRichness = 0,
                                             Quadr_a = 0.00001, Quadr_b = 0.00001,
                                             Cavit_a=0.00001, Cavit_b=0.00001,
                                             Shrub_a=0.00001, Shrub_b=0.00001,
                                             lambda=0.00001),
                no_Quadr_Densi_par_lo = list(PotRichness = 0,
                                             DHeig_a=0.00001, DHeig_b=0.00001,
                                             Cavit_a=0.00001, Cavit_b=0.00001,
                                             Shrub_a=0.00001, Shrub_b=0.00001,
                                             lambda=0.00001),
                compl_no_Shrub_par_lo = list(PotRichness = 0,
                                             Basal_a=0.00001, Basal_b=0.00001, 
                                             DHeig_a=0.00001, DHeig_b=0.00001,
                                             Cavit_a=0.00001, Cavit_b=0.00001,
                                             lambda=0.00001),
                compl_no_Cavit_par_lo = list(PotRichness = 0,
                                             Basal_a=0.00001, Basal_b=0.00001, 
                                             DHeig_a=0.00001, DHeig_b=0.00001,
                                             Shrub_a= 0.00001,Shrub_b=0.000001,
                                             lambda=0.00001),
                compl_no_DHeig_par_lo = list(PotRichness = 0,
                                             Basal_a=0.00001, Basal_b=0.00001, 
                                             Cavit_a=0.00001, Cavit_b=0.00001,
                                             Shrub_a= 0.00001,Shrub_b=0.000001,
                                             lambda=0.00001),
                
                ##### Bivariate low parameters #####
                
                bi_Densi_Quadr_par_lo = list(PotRichness = 0,
                                             Densi_a=0.00001,Densi_b=0.00001,
                                             Quadr_a = 0.00001, Quadr_b = 0.00001,
                                             lambda=0.00001),
                bi_Densi_DHeig_par_lo = list(PotRichness = 0,
                                             Densi_a=0.00001,Densi_b=0.00001,
                                             DHeig_a=0.00001, DHeig_b=0.00001,
                                             lambda=0.00001),
                bi_Densi_Cavit_par_lo = list(PotRichness = 0,
                                             Densi_a=0.00001,Densi_b=0.00001,
                                             Cavit_a=0.00001, Cavit_b=0.00001,
                                             lambda=0.00001),
                bi_Densi_Shrub_par_lo = list(PotRichness = 0,
                                             Densi_a=0.00001,Densi_b=0.00001,
                                             Shrub_a=0.00001, Shrub_b=0.00001,
                                             lambda=0.00001),
                bi_Quadr_DHeig_par_lo = list(PotRichness = 0,
                                             Quadr_a = 0.00001, Quadr_b = 0.00001,
                                             DHeig_a=0.00001, DHeig_b=0.00001,
                                             lambda=0.00001),
                bi_Quadr_Cavit_par_lo = list(PotRichness = 0,
                                             Quadr_a = 0.00001, Quadr_b = 0.00001,
                                             Cavit_a=0.00001, Cavit_b=0.00001,
                                             lambda=0.00001),
                bi_Quadr_Shrub_par_lo = list(PotRichness = 0,
                                             Quadr_a = 0.00001, Quadr_b = 0.00001,
                                             Shrub_a=0.00001, Shrub_b=0.00001,
                                             lambda=0.00001),
                bi_DHeig_Cavit_par_lo = list(PotRichness = 0,
                                             DHeig_a=0.00001, DHeig_b=0.00001,
                                             Cavit_a=0.00001, Cavit_b=0.00001,
                                             lambda=0.00001),
                bi_DHeig_Shrub_par_lo = list(PotRichness = 0,
                                             DHeig_a=0.00001, DHeig_b=0.00001,
                                             Shrub_a=0.00001, Shrub_b=0.00001,
                                             lambda=0.00001),
                bi_Cavit_Shrub_par_lo = list(PotRichness = 0,
                                             Cavit_a=0.00001, Cavit_b=0.00001,
                                             Shrub_a=0.00001, Shrub_b=0.00001,
                                             lambda=0.00001),
                bi_Basal_DHeig_par_lo = list(PotRichness = 0,
                                             Basal_a=0.00001, Basal_b=0.00001, 
                                             DHeig_a=0.00001, DHeig_b=0.00001,
                                             lambda=0.00001),
                bi_Basal_Cavit_par_lo = list(PotRichness = 0,
                                             Basal_a=0.00001, Basal_b=0.00001, 
                                             Cavit_a=0.00001, Cavit_b=0.00001,
                                             lambda=0.00001),
                bi_Basal_Shrub_par_lo = list(PotRichness = 0,
                                             Basal_a=0.00001, Basal_b=0.00001, 
                                             Shrub_a= 0.00001,Shrub_b=0.000001,
                                             lambda=0.00001),
                
                ##### Univariate low parameters #####
                
                univaria_Basal_par_lo = list (PotRichness = 0,
                                              Basal_a = 0.00001, Basal_b = 0.00001, 
                                              lambda = 0.0001),
                univaria_Densi_par_lo = list (PotRichness = 0,
                                         Densi_a = 0.00001, Densi_b = 0.00001, 
                                         lambda = 0.0001),
                univaria_Quadr_par_lo = list (PotRichness = 0,
                                              Quadr_a = 0.00001, Quadr_b = 0.00001, 
                                              lambda = 0.0001),
                univaria_DHeig_par_lo = list (PotRichness = 0,
                                              DHeig_a = 0.00001, DHeig_b = 0.00001, 
                                              lambda = 0.0001),
                univaria_Cavit_par_lo = list (PotRichness = 0,
                                         Cavit_a = 0.00001, Cavit_b = 0.00001, 
                                         lambda = 0.0001),
                univaria_Shrub_par_lo = list (PotRichness = 0,
                                         Shrub_a = 0.00001, Shrub_b = 0.00001, 
                                         lambda = 0.0001),
                univaria_DVari_par_lo = list (PotRichness = 0,
                                              DVari_a = 0.00001, DVari_b = 0.00001, 
                                              lambda = 0.0001),
                univaria_Snags_par_lo = list (PotRichness = 0,
                                              Snags_a = 0.00001, Snags_b = 0.00001, 
                                              lambda = 0.0001),
                univaria_Herba_par_lo = list (PotRichness = 0,
                                              Herba_a = 0.00001, Herba_b = 0.00001, 
                                              lambda = 0.0001),
                univaria_Thick_par_lo = list (PotRichness = 0,
                                              Thick_a = 0.00001, Thick_b = 0.00001, 
                                              lambda = 0.0001))

# High parameters ------------------------------------------------------

        par_high <- list(null_null_null_par_hi = list(PotRichness = 30, 
                                                lambda=100),
                 
                ##### Pentavariate and tetravariate high parameters ####
                 penta_complete_par_hi = list(PotRichness = 25,
                                           Densi_a=10000,Densi_b=10000,
                                           Quadr_a = 60, Quadr_b = 300,
                                           DHeig_a=30, DHeig_b=1000, 
                                           Cavit_a=80, Cavit_b=1000,
                                           Shrub_a=100, Shrub_b=1000,
                                           lambda=100),
                 
                 tetra_no_Shrub_par_hi =  list(PotRichness = 25,
                                               Densi_a=10000,Densi_b=10000,
                                               Quadr_a = 60, Quadr_b = 300,
                                               DHeig_a=30, DHeig_b=1000, 
                                               Cavit_a=80, Cavit_b=1000,
                                               lambda=100),
                 tetra_no_Cavit_par_hi =  list(PotRichness = 25,
                                               Densi_a=10000,Densi_b=10000,
                                               Quadr_a = 60, Quadr_b = 300,
                                               DHeig_a=30, DHeig_b=1000, 
                                               Shrub_a=100, Shrub_b=1000,
                                               lambda=100),
                 tetra_no_DHeig_par_hi =  list(PotRichness = 25,
                                               Densi_a=10000,Densi_b=10000,
                                               Quadr_a = 60, Quadr_b = 300,
                                               Cavit_a=80, Cavit_b=1000,
                                               Shrub_a=100, Shrub_b=1000,
                                               lambda=100),
                 tetra_no_Quadr_par_hi =  list(PotRichness = 25,
                                               Densi_a=10000,Densi_b=10000,
                                               DHeig_a=30, DHeig_b=1000, 
                                               Cavit_a=80, Cavit_b=1000,
                                               Shrub_a=100, Shrub_b=1000,
                                               lambda=100),
                 tetra_no_Densi_par_hi =  list(PotRichness = 25,
                                               Quadr_a = 60, Quadr_b = 300,
                                               DHeig_a=30, DHeig_b=1000, 
                                               Cavit_a=80, Cavit_b=1000,
                                               Shrub_a=100, Shrub_b=1000,
                                               lambda=100),
                tetra_complete_par_hi = list(PotRichness = 25,
                                             Basal_a=100, Basal_b=1000,  
                                             DHeig_a=30, DHeig_b=1000,
                                             Cavit_a=80, Cavit_b=1000,
                                             Shrub_a=100, Shrub_b=1000,
                                             lambda=100),
                
                ##### Trivariate high parameters ####
                
                no_Shrub_Cavit_par_hi =  list(PotRichness = 25,
                                             Densi_a=10000,Densi_b=10000,
                                             Quadr_a = 60, Quadr_b = 300,
                                             DHeig_a=30, DHeig_b=1000, 
                                             lambda=100),
                no_Shrub_DHeig_par_hi =  list(PotRichness = 25,
                                             Densi_a=10000,Densi_b=10000,
                                             Quadr_a = 60, Quadr_b = 300,
                                             Cavit_a=80, Cavit_b=1000,
                                             lambda=100),
                no_Shrub_Quadr_par_hi = list(PotRichness = 25,
                                            Densi_a=10000,Densi_b=10000,
                                            DHeig_a=30, DHeig_b=1000, 
                                            Cavit_a=80, Cavit_b=1000,
                                            lambda=100),
                no_Shrub_Densi_par_hi = list(PotRichness = 25,
                                            Quadr_a = 60, Quadr_b = 300,
                                            DHeig_a=30, DHeig_b=1000, 
                                            Cavit_a=80, Cavit_b=1000,
                                            lambda=100),
                no_Cavit_DHeig_par_hi =  list(PotRichness = 25,
                                             Densi_a=10000,Densi_b=10000,
                                             Quadr_a = 60, Quadr_b = 300,
                                             Shrub_a=100, Shrub_b=1000,
                                             lambda=100),
                no_Cavit_Quadr_par_hi = list(PotRichness = 25,
                                            Densi_a=10000,Densi_b=10000,
                                            DHeig_a=30, DHeig_b=1000, 
                                            Shrub_a=100, Shrub_b=1000,
                                            lambda=100),
                no_Cavit_Densi_par_hi = list(PotRichness = 25,
                                            Quadr_a = 60, Quadr_b = 300,
                                            DHeig_a=30, DHeig_b=1000, 
                                            Shrub_a=100, Shrub_b=1000,
                                            lambda=100),
                no_DHeig_Quadr_par_hi = list(PotRichness = 25,
                                            Densi_a=10000,Densi_b=10000,
                                            Cavit_a=80, Cavit_b=1000,
                                            Shrub_a=100, Shrub_b=1000,
                                            lambda=100),
                no_DHeig_Densi_par_hi = list(PotRichness = 25,
                                            Quadr_a = 60, Quadr_b = 300,
                                            Cavit_a=80, Cavit_b=1000,
                                            Shrub_a=100, Shrub_b=1000,
                                            lambda=100),
                no_Quadr_Densi_par_hi = list(PotRichness = 25,
                                            DHeig_a=30, DHeig_b=1000, 
                                            Cavit_a=80, Cavit_b=1000,
                                            Shrub_a=100, Shrub_b=1000,
                                            lambda=100),
                compl_no_Shrub_par_hi =  list(PotRichness = 25,
                                             Basal_a=100, Basal_b=1000,  
                                             DHeig_a=30, DHeig_b=1000,
                                             Cavit_a=80, Cavit_b=1000,
                                             lambda=100),
                compl_no_Cavit_par_hi =  list(PotRichness = 25,
                                             Basal_a=100, Basal_b=1000,  
                                             DHeig_a=30, DHeig_b=1000,
                                             Shrub_a=100, Shrub_b=1000,
                                             lambda=100),
                compl_no_DHeig_par_hi =  list(PotRichness = 25,
                                             Basal_a=100, Basal_b=1000,  
                                             Cavit_a=80, Cavit_b=1000,
                                             Shrub_a=100, Shrub_b=1000,
                                             lambda=100),
                
                ##### Bivariate high parameters #####
                
                bi_Densi_Quadr_par_hi = list(PotRichness = 25,
                                            Densi_a=10000,Densi_b=10000,
                                            Quadr_a = 60, Quadr_b = 300,
                                            lambda=100),
                bi_Densi_DHeig_par_hi = list(PotRichness = 25,
                                            Densi_a=10000,Densi_b=10000,
                                            DHeig_a=30, DHeig_b=1000, 
                                            lambda=100),
                bi_Densi_Cavit_par_hi = list(PotRichness = 25,
                                            Densi_a=10000,Densi_b=10000,
                                            Cavit_a=80, Cavit_b=1000,
                                            lambda=100),
                bi_Densi_Shrub_par_hi = list(PotRichness = 25,
                                            Densi_a=10000,Densi_b=10000,
                                            Shrub_a=100, Shrub_b=1000,
                                            lambda=100),
                bi_Quadr_DHeig_par_hi = list(PotRichness = 25,
                                            Quadr_a = 60, Quadr_b = 300,
                                            DHeig_a=30, DHeig_b=1000, 
                                            lambda=100),
                bi_Quadr_Cavit_par_hi = list(PotRichness = 25,
                                            Quadr_a = 60, Quadr_b = 300,
                                            Cavit_a=80, Cavit_b=1000,
                                            lambda=100),
                bi_Quadr_Shrub_par_hi = list(PotRichness = 25,
                                            Quadr_a = 60, Quadr_b = 300,
                                            Shrub_a=100, Shrub_b=1000,
                                            lambda=100),
                bi_DHeig_Cavit_par_hi = list(PotRichness = 25,
                                            DHeig_a=30, DHeig_b=1000, 
                                            Cavit_a=80, Cavit_b=1000,
                                            lambda=100),
                bi_DHeig_Shrub_par_hi = list(PotRichness = 25,
                                            DHeig_a=30, DHeig_b=1000, 
                                            Shrub_a=100, Shrub_b=1000,
                                            lambda=100),
                bi_Cavit_Shrub_par_hi = list(PotRichness = 25,
                                            Cavit_a=80, Cavit_b=1000,
                                            Shrub_a=100, Shrub_b=1000,
                                            lambda=100),
                bi_Basal_DHeig_par_hi = list(PotRichness = 25,
                                            Basal_a=100, Basal_b=1000,  
                                            DHeig_a=30, DHeig_b=1000,
                                            lambda=100),
                bi_Basal_Cavit_par_hi = list(PotRichness = 25,
                                            Basal_a=100, Basal_b=1000,  
                                            Cavit_a=80, Cavit_b=1000,
                                            lambda=100),
                bi_Basal_Shrub_par_hi = list(PotRichness = 25,
                                            Basal_a=100, Basal_b=1000,  
                                            Shrub_a=100, Shrub_b=1000,
                                            lambda=100),

                ##### Univariate high parameters ####
                
                univaria_Basal_par_hi = list (PotRichness = 25,
                                             Basal_a = 100, Basal_b = 1000, 
                                             lambda = 100),
                univaria_Densi_par_hi = list (PotRichness = 25,
                                             Densi_a = 2500, Densi_b = 2500, 
                                             lambda = 100),
                univaria_Quadr_par_hi = list (PotRichness = 25,
                                             Quadr_a = 55, Quadr_b = 1000, 
                                             lambda = 100),
                univaria_DHeig_par_hi = list (PotRichness = 25,
                                             DHeig_a = 30, DHeig_b = 100, 
                                             lambda = 100),
                univaria_Cavit_par_hi = list (PotRichness = 25,
                                             Cavit_a = 82, Cavit_b = 1000,
                                             lambda = 100),
                univaria_Shrub_par_hi = list (PotRichness = 25,
                                             Shrub_a = 100, Shrub_b = 1000,
                                             lambda = 100),
                univaria_DVari_par_hi = list (PotRichness = 25,
                                             DVari_a = 100, DVari_b = 1000,
                                             lambda = 100),
                univaria_Snags_par_hi = list (PotRichness = 25,
                                             Snags_a = 2500, Snags_b = 2000,
                                             lambda = 100),
                univaria_Herba_par_hi = list (PotRichness = 25,
                                              Herba_a = 100, Herba_b = 1000,
                                              lambda = 100),
                univaria_Thick_par_hi = list (PotRichness = 25,
                                              Thick_a = 100, Thick_b = 1000,
                                              lambda = 100))
                
                
